"""In-process PostgreSQL-like DB-API driver used to exercise the Postgres code path.

This is NOT a real PostgreSQL server. It emulates the psycopg2 behaviour that
database/database.py depends on:

* ``%s`` placeholders (not ``?``)
* dict-style rows (RealDictCursor)
* ``INSERT ... RETURNING id`` returning a row
* ``fetchone()`` raising when a statement produced no result set
* identity columns instead of AUTOINCREMENT

Storage is a real SQLite file so persistence across application restarts is
genuine rather than in-memory.
"""

from __future__ import annotations

import re
import sqlite3
import sys
import types
from pathlib import Path
from urllib.parse import urlsplit


class ProgrammingError(Exception):
    pass


class RealDictCursor:  # marker only, mirrors psycopg2.extras.RealDictCursor
    pass


def _split_top_level(text: str) -> list[str]:
    """Split on commas that are not inside parentheses or quotes."""
    parts = []
    depth = 0
    quoted = False
    current = []
    for ch in text:
        if ch == "'":
            quoted = not quoted
            current.append(ch)
        elif quoted:
            current.append(ch)
        elif ch == "(":
            depth += 1
            current.append(ch)
        elif ch == ")":
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current).strip())
    return parts


def _column_types(create_sql: str) -> tuple[str, dict[str, str]]:
    match = re.search(r"CREATE TABLE (?:IF NOT EXISTS )?(\w+)\s*\((.*)\)\s*$", create_sql, re.IGNORECASE | re.DOTALL)
    if not match:
        return "", {}
    table = match.group(1).lower()
    columns = {}
    for item in _split_top_level(match.group(2)):
        words = item.split()
        if not words:
            continue
        head = words[0].upper()
        if head in {"FOREIGN", "PRIMARY", "UNIQUE", "CHECK", "CONSTRAINT"}:
            continue
        if len(words) < 2:
            continue
        name = words[0].lower()
        declared = words[1].upper()
        if declared.startswith("INT"):
            columns[name] = "integer"
        elif declared.startswith(("TEXT", "VARCHAR", "CHAR")):
            columns[name] = "text"
        else:
            columns[name] = "other"
    return table, columns


def _check_type(table: str, column: str, value, columns: dict[str, str]) -> None:
    """PostgreSQL will not silently coerce between integer and text columns."""
    declared = columns.get(column)
    if declared is None or value is None:
        return
    if declared == "integer" and isinstance(value, str):
        raise ProgrammingError(
            f'column "{table}.{column}" is of type integer but expression is of type text'
        )
    if declared == "text" and isinstance(value, bool):
        raise ProgrammingError(
            f'column "{table}.{column}" is of type text but expression is of type boolean'
        )
    if declared == "text" and isinstance(value, int) and not isinstance(value, bool):
        raise ProgrammingError(
            f'column "{table}.{column}" is of type text but expression is of type integer'
        )


def _to_sqlite(sql: str) -> str:
    converted = sql.replace("%s", "?")
    converted = converted.replace(
        "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY",
        "INTEGER PRIMARY KEY AUTOINCREMENT",
    )
    return converted


class FakeCursor:
    def __init__(self, connection: "FakeConnection"):
        self._connection = connection
        self._cursor = connection.raw.cursor()
        self._returning: list[dict] | None = None
        self._rows: list[dict] | None = None
        self.lastrowid = None
        self.executed: list[str] = []

    def execute(self, sql, params=None):  # psycopg2 defaults vars to None
        if "?" in sql and "%s" not in sql:
            raise ProgrammingError(f"PostgreSQL driver received a SQLite placeholder: {sql[:120]}")
        # psycopg2 only performs %-interpolation when vars is not None. Passing an
        # empty tuple for parameterless SQL makes any literal % (e.g. LIKE '%x%')
        # explode, so treat that as an error the way a strict driver would.
        if params is not None and len(params) == 0 and "%" in sql:
            raise ProgrammingError(
                "empty parameter sequence passed with a literal %% in the statement; pass None instead"
            )
        self.executed.append(sql)
        self._connection.executed.append(sql)
        self._connection.params.append(params)
        self._connection.learn_schema(sql)
        self._connection.check_types(sql, params)
        statement = _to_sqlite(sql)
        upper = statement.strip().upper()
        if "PG_ADVISORY" in upper:
            # Server-side lock builtin; there is nothing to serialise here.
            self._returning = None
            self._rows = [{"pg_advisory_xact_lock": None}]
            return
        wants_returning = " RETURNING ID" in upper
        if wants_returning:
            statement_no_returning = re.sub(r"\s+RETURNING\s+id\s*$", "", statement, flags=re.IGNORECASE)
            self._cursor.execute(statement_no_returning, tuple(params or ()))
            # psycopg2 exposes lastrowid as an OID, which is 0/None for ordinary
            # tables. RETURNING is the only way to learn the new id.
            self.lastrowid = None
            self._returning = [{"id": self._cursor.lastrowid}]
            self._rows = None
            return
        self._cursor.execute(statement, tuple(params or ()))
        self._returning = None
        if self._cursor.description:
            columns = [d[0] for d in self._cursor.description]
            self._rows = [dict(zip(columns, row)) for row in self._cursor.fetchall()]
        else:
            self._rows = None

    def fetchone(self):
        if self._returning is not None:
            return self._returning.pop(0) if self._returning else None
        if self._rows is None:
            raise ProgrammingError("no results to fetch")
        return self._rows.pop(0) if self._rows else None

    def fetchall(self):
        if self._rows is None:
            if self._returning is not None:
                rows, self._returning = self._returning, []
                return rows
            raise ProgrammingError("no results to fetch")
        rows, self._rows = self._rows, []
        return rows

    def close(self):
        self._cursor.close()


class FakeConnection:
    def __init__(self, path: str, schema: dict | None = None):
        self.raw = sqlite3.connect(path)
        self.raw.execute("PRAGMA foreign_keys = ON")
        self.executed: list[str] = []
        self.params: list = []
        self.commits = 0
        self.rollbacks = 0
        # Tables live in one shared database, so the learned column types must be
        # shared across connections too.
        self.schema: dict[str, dict[str, str]] = schema if schema is not None else {}
        self._cursors: list[FakeCursor] = []

    def learn_schema(self, sql: str) -> None:
        if sql.strip().upper().startswith("CREATE TABLE"):
            table, columns = _column_types(sql.strip().rstrip(";"))
            if table:
                self.schema[table] = columns

    def check_types(self, sql: str, params) -> None:
        if not params:
            return
        text = sql.strip()
        insert = re.match(
            r"INSERT INTO (\w+)\s*\(([^)]*)\)\s*VALUES\s*\((.*?)\)(?:\s|$)", text, re.IGNORECASE | re.DOTALL
        )
        if insert:
            table = insert.group(1).lower()
            columns = self.schema.get(table)
            if not columns:
                return
            names = [c.strip().lower() for c in insert.group(2).split(",")]
            values = _split_top_level(insert.group(3))
            remaining = list(params)
            for name, value_expr in zip(names, values):
                if value_expr.strip() != "%s":
                    continue
                if not remaining:
                    break
                _check_type(table, name, remaining.pop(0), columns)
            return
        update = re.match(r"UPDATE (\w+)\s+SET\s+(.*?)(?:\s+WHERE\s|$)", text, re.IGNORECASE | re.DOTALL)
        if update:
            table = update.group(1).lower()
            columns = self.schema.get(table)
            if not columns:
                return
            remaining = list(params)
            for assignment in _split_top_level(update.group(2)):
                name, _, value_expr = assignment.partition("=")
                if value_expr.strip() != "%s" or not remaining:
                    continue
                _check_type(table, name.strip().lower(), remaining.pop(0), columns)

    def cursor(self, *args, **kwargs):
        cursor = FakeCursor(self)
        self._cursors.append(cursor)
        return cursor

    def commit(self):
        self.commits += 1
        self.raw.commit()
        # A RETURNING result must be consumed before the transaction is closed.
        for cursor in self._cursors:
            cursor._returning = None

    def rollback(self):
        self.rollbacks += 1
        self.raw.rollback()

    def close(self):
        self.raw.close()


def install(monkeypatch, storage_path: Path):
    """Register a fake ``psycopg2`` module backed by ``storage_path``."""

    storage_path.parent.mkdir(parents=True, exist_ok=True)
    connections: list[FakeConnection] = []
    shared_schema: dict[str, dict[str, str]] = {}

    def connect(dsn, cursor_factory=None, **kwargs):
        parts = urlsplit(dsn)
        if parts.scheme not in {"postgresql", "postgres"}:
            raise ProgrammingError(f"unexpected scheme {parts.scheme!r}")
        connection = FakeConnection(str(storage_path), schema=shared_schema)
        connections.append(connection)
        return connection

    module = types.ModuleType("psycopg2")
    module.connect = connect
    module.ProgrammingError = ProgrammingError
    extras = types.ModuleType("psycopg2.extras")
    extras.RealDictCursor = RealDictCursor
    module.extras = extras

    monkeypatch.setitem(sys.modules, "psycopg2", module)
    monkeypatch.setitem(sys.modules, "psycopg2.extras", extras)
    return connections
