#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for SpeakEd.
# Creates a virtualenv, installs pinned dependencies, and writes a local
# development .env (gitignored) with a generated SECRET_KEY when one is missing.
set -euo pipefail

cd "$(dirname "$0")/.."

PY="${PYTHON:-python3}"

if [ ! -x ".venv/bin/python" ]; then
  "$PY" -m venv .venv
fi

./.venv/bin/pip install --upgrade pip
./.venv/bin/pip install -r requirements.txt

# Local development configuration. Never committed (see .gitignore). Uses a
# freshly generated SECRET_KEY, the offline rule-based marker, and open signup
# so the app is fully usable without any external API keys or secrets.
if [ ! -f ".env" ]; then
  SECRET_KEY="$(./.venv/bin/python -c 'import secrets; print(secrets.token_urlsafe(48))')"
  cat > .env <<EOF
# Local development environment for SpeakEd (auto-generated by .cursor/install.sh).
# Regenerate by deleting this file and re-running the install step.
AI_PROVIDER=rule
FLASK_DEBUG=1
SECRET_KEY=${SECRET_KEY}
# DATABASE_URL is intentionally unset so the app uses a local SQLite database.
# Open signup for local development so any account can be created and explored.
PRIVATE_MODE=false
EOF
  echo "Wrote local development .env"
fi

echo "SpeakEd install complete."
